variables:
  majorVersion: '1.0'
  minorVersion: $[counter('minorVersion', 2)]
  version: '$(majorVersion).$(minorVersion)'
  buildName: '$(Build.SourceBranchName).$(version)'

trigger:
  branches:
    include:
    - master

pr:
- master

jobs:
- job:
  displayName: Setup
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - powershell: Write-Host "##vso[build.updatebuildnumber]$($env:VERSION)"
    displayName: Set Build Name

- job:
  displayName: Build sir
  pool:
    vmImage: 'Ubuntu-18.04'
  steps:
  - task: Docker@2
    displayName: Build image
    inputs:
      containerRegistry: 'ghcr'
      repository: lidarr/mb-sir
      command: buildAndPush
      Dockerfile: Dockerfile
      tags: |
        latest
        $(Build.SourceBranchName)
        $(version)
